apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-config
  namespace: vikunja
data:
  VIKUNJA_DATABASE_TYPE: postgres
  VIKUNJA_DATABASE_HOST: postgres
  VIKUNJA_DATABASE_DATABASE: vikunja
  VIKUNJA_DATABASE_USER: vikunja
  VIKUNJA_SERVICE_PUBLICURL: http://vikunja.local
  VIKUNJA_SERVE_FRONTEND: "false"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: vikunja
data:
  POSTGRES_DB: vikunja
  POSTGRES_USER: vikunja
